AllCops:
  TargetRubyVersion: 3.2.1
  NewCops: disable
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
#Style/CommentedKeyword:
#  Enabled: false
#Metrics/BlockLength:
#  Max: 60
#Metrics/MethodLength:
#  Max: 15
#Layout/LeadingCommentSpace:
#  Enabled: false
